services:
  ucar-db:
    image: postgres:16-alpine
    hostname: ucar-db
    container_name: ucar-db
    shm_size: 1g
    user: ${POSTGRES_USER}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5433:5432
    networks:
      - ucar_net
    env_file:
      - ./.env

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${LOCAL_PORT}:${LOCAL_PORT}
    command: uvicorn main:app --host ${LOCAL_HOST} --port ${LOCAL_PORT} --workers 1
    depends_on:
      - ucar-db
    networks:
      - ucar_net

volumes:
  postgres_data:

networks:
  ucar_net:
    driver: bridge
